{% set version = "3.1.1" %}

package:
  name: cfchecker
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cfchecker/cfchecker-{{ version }}.tar.gz
  sha256: bea971f3653769209f0368c9720c98c9a0b112d3522ac2c02330e0df23103f33

build:
  skip: True  # [win or py3k]
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - cfchecks = cfchecker.cfchecks:main

requirements:
  host:
    - python
    - pip
    - numpy
    - netcdf4
    - cfunits
  run:
    - python
    - setuptools
    - numpy
    - netcdf4
    - cfunits

test:
  commands:
    - cfchecks -h
  imports:
    - cfchecker

about:
  home: https://pypi.python.org/pypi/cfchecker
  license: BSD-3-Clause
  summary: The NetCDF Climate Forcast Conventions compliance checker

extra:
  recipe-maintainers:
    - ocefpaf
    - agstephens
