{% set version = "3.1.3" %}

package:
  name: cfchecker
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cfchecker/cfchecker-{{ version }}.tar.gz
  sha256: 07bf90e21e457c8977877c5a37debd9d9c8c34c50c0c40246c21fd46ad532881

build:
  skip: True  # [win or py3k]
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - cfchecks = cfchecker.cfchecks:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - netcdf4
    - numpy >=1.7,<1.17
    - cfunits >=1.1.4,<3.0.0

test:
  commands:
    - cfchecks -h
  imports:
    - cfchecker

about:
  home: https://pypi.python.org/pypi/cfchecker
  license: BSD-3-Clause
  license_file: LICENSE
  summary: The NetCDF Climate Forcast Conventions compliance checker

extra:
  recipe-maintainers:
    - ocefpaf
    - agstephens
