{% set version = "4.1.0" %}

package:
  name: cfchecker
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cfchecker/cfchecker-{{ version }}.tar.gz
  sha256: 10b86748565c9e0f4c959e4d82fe83b00344551db3db3c7d0d2f8c31449aa1b9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - cfchecks = cfchecker.cfchecks:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - netcdf4
    - numpy >=1.7
    - cfunits >=3.0.0
    - future

test:
  requires:
    - pip
  commands:
    - pip check
    - cfchecks -h
  imports:
    - cfchecker

about:
  home: https://pypi.python.org/pypi/cfchecker
  license: BSD-3-Clause
  license_file: LICENSE
  summary: The NetCDF Climate Forcast Conventions compliance checker

extra:
  recipe-maintainers:
    - ocefpaf
    - agstephens
