appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: rE2YSco/xiVlXi0R0m7JXDLa3EZ2IhgJp3jQF8W6iP9ttvip5o/N4QA5rN6onm/tY8bReqUKiCkTYd7Vrp4EP31MbMrXshaC9FvlmLTxyYmnepMGKC8/2UZDhvTMAJH+IU8ilkVZBRgmw613WhmPCRS+UeAuqGnXv/A2hXqGsYViV3jB0wU4uuTr88KkOThA4Y9BCq8pnyQdpTBI77QHHS+WYQmL0eLOcJfOezYf7e+800T9XYyPxNorQYcd68xgSLVCLFh5Be8E/lB6dYt2p7xsWHJ7uaZeHlICTjnncfVdmmXuXvurZAA5rWSSqyECPpccyx6zp32aI5PG2euL7DwQGLS7Z7kYr8vDa+cqjesmUR8PapieeMEh1ym6rTjiqlToRflYjEU9RW9NynTIK+7QOVwhxCmbJgK5ItyvfRaSymDxwqcnHigOR52xD6sqJMQylAMrHC+VW+RVTOwlOZQ3bnv7XUc8Ac2ri7lgiIpB336lf4yWjwTwMgKg1UETnTUD8mOssO0DsUqHT154cDvIxsopjY1QuzQ28bpMrkFl01b8thoeR9dL23Esj9dd/Bap33OGiRMXl/5jKZ4g4gjNMkVUDbkA9iAedPMy5+jqbuG9QNdCfx51Zr8oG6Jt1ACbC5RjPmd6iEUMBB8o9buHbnpxVrmqKVp+x0RKl/U=}
